ROBLOX_TOKEN_KEY = ".ROBLOSECURITY"
ROBLOX_HOME_URL = "https://www.roblox.com/home"

DEFAULT_QUEUE_NAME = "url_queue"
DEFAULT_EXCHANGE_NAME = "url"
DEFAULT_ROUTING_KEY = DEFAULT_QUEUE_NAME
DEFAULT_SEND_NAME = DEFAULT_QUEUE_NAME + "_return"
DEFAULT_SEND_EXCHANGE_NAME = DEFAULT_EXCHANGE_NAME + "_return"
DEFAULT_THREADS_COUNT = 2

TOKEN_RECURSIVE_CHECK = 5

